add_newline = false
command_timeout = 1000

format = """
╭─$username\
$hostname\
$directory\
${custom.jj}\
$time\
$cmd_duration
╰─$character"""

[username]
show_always = true
style_user = "bg:#af3a03 fg:white"
style_root = "bg:#cc241d fg:white"
format = "[](fg:#af3a03)[$user]($style)[](fg:#af3a03 bg:#9d6a06)"

[hostname]
ssh_only = false
style = "bg:#9d6a06 fg:white"
format = "[$hostname]($style)[](fg:#9d6a06 bg:#076678)"
trim_at = "."
disabled = false

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bg:#076678 fg:white"
format = "[$path]($style)[](fg:#076678 bg:#8f3f71)"

[custom.jj]

command = "jj log -r @ -n 1 --no-graph --template \"change_id.shortest(8) ++ '  ' ++ commit_id.shortest(8) ++ if(bookmarks, '  ' ++ bookmarks)\""

detect_folders = [".jj"]

style = "bg:#8f3f71 fg:white"

format = "[$output]($style)[](fg:#8f3f71 bg:#665c54)"

[time]
disabled = false
time_format = "%y-%m-%d - %T"
style = "bg:#665c54 fg:white"
format = "[$time]($style)[](fg:#665c54)"

[character]
success_symbol = "[⠠⠵](bold green)"
error_symbol = "[⠠⠵](bold red)"
